/**
 * Auto-bootstrap FOUNDEROS_AGENT_JWT_SECRET in development / test environments.
 *
 * Why this exists:
 *   The local-agent JWT secret is required for any adapter that declares
 *   `supportsLocalAgentJwt: true` (claude_local, codex_local, cursor, etc.).
 *   Pre-2026-05-09, missing-secret was a silent-degradation footgun:
 *   `createLocalAgentJwt` returned null, the heartbeat dropped `authToken`,
 *   and the spawned agent ran without `FOUNDEROS_API_KEY` in env — every
 *   authenticated API call from the agent returned 401, surfacing as a
 *   confusing 401 in the agent's own output.
 *
 *   PR #109 made the runtime path hard-fail (heartbeat throws at adapter
 *   spawn time). This module closes the dev-experience gap: a fresh
 *   `git clone && pnpm dev` should not trip a 401 on first agent run just
 *   because the founder hasn't run `pnpm founderos onboard` yet.
 *
 * Production behavior:
 *   `validateEnvOrExit({ strict: true })` in `index.ts` already hard-fails
 *   the boot when the secret is missing under NODE_ENV=production, so this
 *   module is functionally a no-op in prod (the env-validation gate fires
 *   first). The defensive throw in this module is belt-and-suspenders for
 *   the case where validateEnvOrExit is bypassed.
 *
 * Dev/test behavior:
 *   Generate a 32-byte hex secret, write to ~/.founderos/.env (mode 0600),
 *   inject into process.env. Subsequent boots read the persisted secret.
 *
 * Wire-up: call `ensureAgentJwtSecretAtBoot()` from `index.ts` AFTER
 * `loadConfig()` (which loads dotenv from ~/.founderos/.env and CWD/.env)
 * but BEFORE `validateEnvOrExit()` so prod sees the same env-validation
 * outcome whether the bootstrap fired or not.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { randomBytes } from "node:crypto";
import { parse as parseEnvFileContents } from "dotenv";
import { resolveFounderOSEnvPath } from "../paths.js";

const JWT_SECRET_ENV_KEY = "FOUNDEROS_AGENT_JWT_SECRET";

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.trim().length > 0;
}

function readSecretFromEnvFile(filePath: string): string | null {
  let content: string;
  try {
    content = readFileSync(filePath, "utf-8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return null;
    // Other errors (EACCES, EISDIR, symlink loops, etc.) → treat as
    // unreadable so the bootstrap regenerates rather than crashes.
    return null;
  }
  try {
    const parsed = parseEnvFileContents(content);
    const value = parsed[JWT_SECRET_ENV_KEY];
    return isNonEmptyString(value) ? value.trim() : null;
  } catch {
    return null;
  }
}

function formatEnvValue(value: string): string {
  // Mirror cli/src/config/env.ts so dotenv can round-trip values that
  // contain # / quotes / spaces. Hex secrets always match the safe class.
  if (/^[A-Za-z0-9_./:@-]+$/.test(value)) {
    return value;
  }
  return JSON.stringify(value);
}

function appendOrCreateEnvFile(filePath: string, secret: string): void {
  // Read existing entries (if any), merge in the new secret, rewrite.
  // Keeps any unrelated entries (e.g., FOUNDEROS_WORKTREE_COLOR) intact.
  const dir = dirname(filePath);
  mkdirSync(dir, { recursive: true });

  const existing: Record<string, string> = (() => {
    let content: string;
    try {
      content = readFileSync(filePath, "utf-8");
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === "ENOENT") return {};
      return {}; // unreadable for any reason → start fresh
    }
    try {
      return parseEnvFileContents(content);
    } catch {
      return {};
    }
  })();

  const merged = { ...existing, [JWT_SECRET_ENV_KEY]: secret };
  const lines = [
    "# FounderOS environment variables",
    "# Generated by FounderOS server boot (jwt-secret-bootstrap)",
    ...Object.entries(merged).map(([key, value]) => `${key}=${formatEnvValue(value)}`),
    "",
  ];
  writeFileSync(filePath, lines.join("\n"), { mode: 0o600 });
}

export interface BootstrapResult {
  /** True when this call generated and persisted a new secret. */
  created: boolean;
  /** True when the secret was loaded from disk (already existed). */
  loadedFromFile: boolean;
  /** Path to the env file that was read or written. */
  envFilePath: string;
}

/**
 * Ensure FOUNDEROS_AGENT_JWT_SECRET is present in process.env before any
 * authenticated agent path runs.
 *
 * Production: throws if the secret is missing. (env-validation.ts also
 * fails the boot earlier — this is defensive belt-and-suspenders.)
 *
 * Dev/test: auto-bootstrap. If a secret already exists in the .env file,
 * load it. Otherwise generate `randomBytes(32).toString("hex")`, persist
 * to ~/.founderos/.env (mode 0600), and inject into process.env.
 *
 * @returns metadata about what happened — for logging at boot.
 */
export function ensureAgentJwtSecretAtBoot(opts?: {
  envFilePath?: string;
}): BootstrapResult {
  const envFilePath = opts?.envFilePath ?? resolveFounderOSEnvPath();

  // Fast path: already in process.env (e.g., set explicitly via Fly secret,
  // CI env var, or pre-loaded by config.ts dotenv).
  const envValue = process.env[JWT_SECRET_ENV_KEY];
  if (isNonEmptyString(envValue)) {
    return { created: false, loadedFromFile: false, envFilePath };
  }

  if (process.env.NODE_ENV === "production") {
    // env-validation.ts already refuses to boot in this case under strict
    // mode; this throw is the defensive double-check for any code path
    // that imports this module without validateEnvOrExit having fired.
    throw new Error(
      "FOUNDEROS_AGENT_JWT_SECRET must be set in production. " +
        "Set it via `fly secrets set FOUNDEROS_AGENT_JWT_SECRET=...` " +
        "or via your platform's secret manager. " +
        "Refusing to auto-generate a secret in production — that would " +
        "rotate the key on every deploy and invalidate every in-flight " +
        "agent JWT.",
    );
  }

  // Dev/test path. Try to read an existing secret from the env file first
  // (covers the case where config.ts's dotenv didn't fire because the file
  // was created after config module-load).
  const fileSecret = readSecretFromEnvFile(envFilePath);
  if (fileSecret) {
    process.env[JWT_SECRET_ENV_KEY] = fileSecret;
    return { created: false, loadedFromFile: true, envFilePath };
  }

  // No secret anywhere. Generate one and persist it.
  const generated = randomBytes(32).toString("hex");
  appendOrCreateEnvFile(envFilePath, generated);
  process.env[JWT_SECRET_ENV_KEY] = generated;
  return { created: true, loadedFromFile: false, envFilePath };
}
